<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYidgeFT\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYidgeFT/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYidgeFT.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYidgeFT\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYidgeFT\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YidgeFT',
    'container.build_id' => '6b8e0122',
    'container.build_time' => 1560899178,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYidgeFT');
